name: Terraform CI

on:
  pull_request:
    branch: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.44.1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Valdiate
        id: validate
        run: terraform validate

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
 
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
          -var="account_id=${{ secrets.ACCOUNT_ID }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="mx_domain_1=${{ secrets.MX_DOMAIN_1 }}" \
          -var="mx_domain_2=${{ secrets.MX_DOMAIN_2 }}" \
          -var="mx_domain_3=${{ secrets.MX_DOMAIN_3 }}" \
          -var="spf_domain=${{ secrets.SPF_DOMAIN }}" \
          -var="legacy_website_ip=${{ secrets.LEGACY_WEBSITE_IP }}" \
          -var="recaptcha_secret=${{ secrets.RECAPTCHA_SECRET }}" \
          -var="receiver_email=${{ secrets.RECEIVER_EMAIL }}" \
          -var="sender_email=${{ secrets.SENDER_EMAIL }}"
