name: Terraform CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply \
          -var="account_id=${{ secrets.ACCOUNT_ID }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="domain_name_dot_com=${{ secrets.DOMAIN_NAME_DOT_COM }}" \
          -var="mx_domain_1=${{ secrets.MX_DOMAIN_1 }}" \
          -var="mx_domain_2=${{ secrets.MX_DOMAIN_2 }}" \
          -var="mx_domain_3=${{ secrets.MX_DOMAIN_3 }}" \
          -var="spf_domain=${{ secrets.SPF_DOMAIN }}" \
          -var="recaptcha_secret=${{ secrets.RECAPTCHA_SECRET }}" \
          -var="receiver_email=${{ secrets.RECEIVER_EMAIL }}" \
          -var="sender_email=${{ secrets.SENDER_EMAIL }}" \
          -auto-approve
